### ISSUE TITLE
marshaling error complex objects

### ISSUE THREAD

**Issue by eaddingtonwhite** [momentohq/simple-spring-memcached#8]
Need to come up with better strategy for which marshaler to use by default.

<img width="841" alt="Screen Shot 2022-03-01 at 8 22 52 PM" src="https://user-images.githubusercontent.com/5491827/156294630-617759cb-8146-4b2d-8b12-e54d65aef164.png">

**Comment by kvcache** [comment]
Oh Java is there no escape from jackson objectmapper

**Comment by tylerburdsall** [comment]
Okay so I think I figured the issue here, when we are performing `gets` we are incorrectly setting the `CacheData`s flag to `0`:

* [here](https://github.com/momentohq/simple-spring-memcached/blob/momento/momento-provider/src/main/java/com/google/code/ssm/providers/momento/MomentoClientWrapper.java#L107)
* [here](https://github.com/momentohq/simple-spring-memcached/blob/momento/momento-provider/src/main/java/com/google/code/ssm/providers/momento/MomentoClientWrapper.java#L130)
* [And here, where we are just setting the flag to the length of bytes (this was a mistake made during my early implementations of the wrapper)](https://github.com/momentohq/simple-spring-memcached/blob/momento/momento-provider/src/main/java/com/google/code/ssm/providers/momento/MomentoClientWrapper.java#L148)

We need to figure out how to determine upon doing a `get` what the flag is of the cached data

**Comment by tylerburdsall** [comment]
Ah okay, so here's what's going on:

1. When our transcoder is calling `encode`, we are actually serializing up all of the data from a wrapped `CachedData` object which contains things like an `int` flag and the actual `byte[]` of data.
2. When we call `decode` we can extract the flag by doing some bit-masking on the first `int` of byte data
3. Knowing the flag, we can pass along the raw `byte[]` (including the flag) to the transcoder and it will it properly decode back to our specified `T` type

I'll have a PR up with this fix and this should help unblock issues faced with this
